# Generated by Django 4.0.2 on 2022-02-15 21:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_job_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 21, 14, 24, 999518, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
