# Generated by Django 4.0.2 on 2022-02-15 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_alter_job_date_added_alter_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
