# Generated by Django 4.0.2 on 2022-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0006_alter_job_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
